apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nerdy-jokes-app
  namespace: ingress-nginx
  labels:
    app:
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: ingress-nginx
  endpoints:
    - port: prometheus
