spring:
  profiles:
    active: dev
management:
  endpoint:
    health:
      probes:
        enabled: true
      show-details: "always"
      group:
        local:
          include: "diskSpace,ping"
  endpoints:
    web:
      exposure:
        include: "*"
---
spring:
  profiles: dev
  main:
    banner-mode: "console"
logging:
  level:
    web: 'INFO'
    root: 'INFO'
---
spring:
  profiles: prod
  main:
    banner-mode: "off"
  devtools:
    add-properties: false
