apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus
  namespace: dev
  labels:
    app: nerdy-jokes-app
spec:
  selector:
    matchLabels:
      operated-prometheus: "true"
  endpoints:
    - port: web
