apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus
  namespace: monitoring
  labels:
    app: nerdy-jokes-app
spec:
  selector:
    matchLabels: {}
  endpoints:
    - port: web
    - port: http
