apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: grafana
  namespace: monitoring
  labels:
    app: nerdy-jokes-app
spec:
  selector:
    matchLabels: {}
  endpoints:
    - port: grafana
    - port: http-metrics
